// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropMoviesAndAddGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropMoviesAndAddGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140119348_Drop-Movies-And-Add-Genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
